- name: declare a variable at play level
  hosts: all
  connection: local
  vars:
    url: play.example.com
  tasks:
    - name: access a variable
      ansible.builtin.debug:
        msg: url == {{url}}


- name: declare a variable in anotherfile
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: access variable
      ansible.builtin.debug:
        msg: url == {{url}}

- name: access a fact
  hosts: all
  connection: local
  tasks:
    - name: access facts
      ansible.builtin.debug:
        msg: ansible hostname == {{ansible_fqdn}}